### PR TITLE
extended log messaging / Ladder MC bugfix

### PR DESCRIPTION
**Pull request by werthm**

### CODE REVIEW

**Comment by neiser** [comment]
I think @ppmartel should check if this Tagger ladder fix is ok (I remember he worked on this, too). Why do we still use fixed arrays of chars like the tmp variable? Last time I fixed a bug related to this. std::stringstream is a much better alternative!

**Comment by werthm** [comment]
Doesn't really matter in my opinion as AcquRoot is still full of such code. If you insist I can change that after doing some performance tests first since std::stringstream is usually slower than sprintf.

**Comment by neiser** [comment]
Yes, I insist! This part is not performance critical at all since it's config setup stuff. And just because AcquRoot still uses a lot of those dangerous sprintf stuff is a reason to introduce even more of those pitfalls? And we had already such a bug, see 363dbbcc8bd76f2b30112080f7f3e6b775762215

**Comment by werthm** [comment]
No, the logging functions could have been called quite often (undefined ADC) without this new mechanism for stopping it after a maximum number of messages. What about TString::Format()? That's save as well, right?

**Comment by ppmartel** [comment]
I agree that we should avoid adding more buggy code, as then it allows us (albeit slowly) to fix the bugs that still exist in the code. How to implement this in this case, I'll leave to those who know more about the speed limitations of various functions.

Regarding the Ladder fix, I see your idea, but with my edits I was trying to move away from IsOverlap determining both whether to create doubles (in the case of MC) and whether to decode them. I think the MC should always create the doubles, as this more accurately represents real data, and is actually a non-negligible effect. If one really wants to have the MC not create doubles for whatever reason, one could always set all the widths to zero.

**Comment by werthm** [comment]
Commit f912b4d introduces the safer std::stringstream in the log messaging.

50b6208 fixes a severe bug that was apparently present since a long time ago and basically broke the tagger double decoding.

Finally, commit 9f27608 enables support for both cases (with/without overlaps) in the MC decoding of the tagger. Overlaps are now correctly recognized and reduces to one hit. If overlaps are disabled the "electron hit" is assigned randomly to one of the overlapping tagger channels.

**Comment by ppmartel** [comment]
I agree with 50b6208. I'm still not sure about 9f27608 though, since I think it's a bit funny to treat MC and real data differently based on this switch.

For real data: when IsOverlaps is false it has doubles but does not try to decode them, and when IsOverlaps is true it tries to decode them.

For MC: when IsOverlaps is false it does not have doubles, and when IsOverlaps is true it has doubles and tries to decode them.

I just feel that this can lead (and has led) to confusion. Why do you prefer it to work this way?

**Comment by werthm** [comment]
I restored Phi's original TA2Ladder.cc and fixed another bug in TA2Ladder.h (DecodeDoubles)

**Comment by ppmartel** [comment]
This seems fine to me. Andreas, do you agree with the error logging stuff now?

**Comment by neiser** [comment]
Yes, looks good now.

**Pull request merged**
